site_name: My Docs
site_url: https://bishowlovespython.github.io/
theme:
  name: material
  logo: assets/logo/logo.png
  favicon: assets/logo/logo.png
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
    - header.autohide
    - navigation.footer
    - content.code.copy
    - content.code.select
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: black
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - blog
  - search
  - glightbox
  - mkdocs-video

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details

  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex

nav:
  - Blog:
      - blog/index.md

  - Built-in:
      - Overview: built-in/overview.md
      - dir() function: built-in/dir-function.md

  - Cheatsheet:
      - JS vs PY: cheatsheet/js-vs-py.md
      - Similarities: cheatsheet/similarities.md
      - Differences: cheatsheet/differences.md
      - Concept: cheatsheet/concept.md
